-- SPCS infrastructure (run as ACCOUNTADMIN on the submission account)
CREATE SCHEMA IF NOT EXISTS OEE_DB.CONTAINERS;
CREATE IMAGE REPOSITORY IF NOT EXISTS OEE_DB.CONTAINERS.OEE_REPOSITORY;
CREATE STAGE IF NOT EXISTS OEE_DB.CONTAINERS.SERVICE_SPECS
  DIRECTORY = (ENABLE = TRUE);
CREATE COMPUTE POOL IF NOT EXISTS OEE_UI_POOL
  MIN_NODES = 1 MAX_NODES = 1
  INSTANCE_FAMILY = CPU_X64_XS
  AUTO_RESUME = TRUE
  AUTO_SUSPEND_SECS = 300
  INITIALLY_SUSPENDED = TRUE;
SHOW IMAGE REPOSITORIES IN SCHEMA OEE_DB.CONTAINERS;  -- note repository_url
