-- After image push + spec upload:
CREATE SERVICE IF NOT EXISTS OEE_DB.CONTAINERS.FORGEPULSE_CONSOLE
  IN COMPUTE POOL OEE_UI_POOL
  FROM @OEE_DB.CONTAINERS.SERVICE_SPECS
  SPECIFICATION_FILE = 'spec.yml'
  MIN_INSTANCES = 1 MAX_INSTANCES = 1
  QUERY_WAREHOUSE = OEE_WH;

-- watch it start (repeat until READY):
SELECT SYSTEM$GET_SERVICE_STATUS('OEE_DB.CONTAINERS.FORGEPULSE_CONSOLE');
-- logs if it fails:
-- CALL SYSTEM$GET_SERVICE_LOGS('OEE_DB.CONTAINERS.FORGEPULSE_CONSOLE', 0, 'console', 100);

-- the public URL:
SHOW ENDPOINTS IN SERVICE OEE_DB.CONTAINERS.FORGEPULSE_CONSOLE;
