-- 04_diagnose.sql — OEE Command Center diagnose layer (G1 spine)
-- Doctrine: retrieval owns grounding, LLM owns reasoning.
-- The proc assembles the evidence dossier deterministically in SQL;
-- Cortex COMPLETE writes the narrative FROM THAT EVIDENCE ONLY.
-- All names fully qualified (CoCo session context does not persist).

-- ── Diagnose procedure ──────────────────────────────────────────────────────
-- For each ANOMALY_EVENT in status NEW with no finding yet:
--   evidence = detection features + matching corrective WOs (same mode)
--              + last corrective WO on this asset + MTBF context + asset row
--   finding  = COMPLETE(narrative from evidence) → ANALYTICS.FINDINGS
--   event    → INVESTIGATING
-- Idempotent: one finding per event (the LLM-spend loop guard).
-- G1 retrieval = structured WO match; G1.5 swaps in Cortex Search over
-- OCR'd repair reports without touching anything else.

CREATE OR REPLACE PROCEDURE OEE_DB.ANALYTICS.DIAGNOSE_FINDINGS()
RETURNS VARCHAR
LANGUAGE SQL
AS
$$
DECLARE
  n_new INTEGER DEFAULT 0;
  n_done INTEGER DEFAULT 0;
BEGIN
  SELECT COUNT(*) INTO :n_new
  FROM OEE_DB.ANALYTICS.ANOMALY_EVENTS e
  WHERE e.status = 'NEW'
    AND NOT EXISTS (SELECT 1 FROM OEE_DB.ANALYTICS.FINDINGS f
                    WHERE f.event_id = e.event_id);
  IF (n_new = 0) THEN
    RETURN 'No new events to diagnose.';
  END IF;

  -- 1) Build the evidence dossier per event, deterministically.
  CREATE OR REPLACE TEMPORARY TABLE _DOSSIER AS
  WITH new_events AS (
    SELECT e.event_id, e.asset_id, e.probable_mode, e.severity,
           e.days_to_threshold, e.feature_json, e.detected_ts
    FROM OEE_DB.ANALYTICS.ANOMALY_EVENTS e
    WHERE e.status = 'NEW'
      AND NOT EXISTS (SELECT 1 FROM OEE_DB.ANALYTICS.FINDINGS f
                      WHERE f.event_id = e.event_id)
  ),
  mode_history AS (          -- fleet-wide corrective WOs matching the mode
    SELECT ne.event_id,
           ARRAY_AGG(OBJECT_CONSTRUCT(
             'wo_id', w.wo_id, 'asset_id', w.asset_id,
             'opened', TO_VARCHAR(w.opened_ts,'YYYY-MM-DD'),
             'downtime_hours', w.downtime_hours,
             'parts_used', w.parts_used,
             'notes', LEFT(w.technician_notes, 400)))
             WITHIN GROUP (ORDER BY w.opened_ts DESC) AS matching_wos
    FROM new_events ne
    JOIN OEE_DB.ERP.WORK_ORDER_HISTORY w
      ON w.failure_mode = ne.probable_mode AND w.wo_type = 'CORRECTIVE'
    GROUP BY ne.event_id
  ),
  last_wo AS (               -- most recent corrective WO on THIS asset
    SELECT ne.event_id,
           MAX(w.closed_ts) AS last_corrective_ts,
           DATEDIFF(day, MAX(w.closed_ts), ne.detected_ts) AS days_since_last
    FROM new_events ne
    LEFT JOIN OEE_DB.ERP.WORK_ORDER_HISTORY w
      ON w.asset_id = ne.asset_id AND w.wo_type = 'CORRECTIVE'
    GROUP BY ne.event_id, ne.detected_ts
  )
  SELECT ne.event_id, ne.asset_id, ne.probable_mode, ne.severity,
         ne.days_to_threshold,
         OBJECT_CONSTRUCT(
           'detection_features', ne.feature_json,
           'asset', OBJECT_CONSTRUCT('asset_id', am.asset_id,
                    'name', am.asset_name, 'type', am.asset_type,
                    'line', am.line_id, 'model', am.model_no,
                    'installed', TO_VARCHAR(am.install_date),
                    'criticality', am.criticality),
           'matching_work_orders', COALESCE(mh.matching_wos, ARRAY_CONSTRUCT()),
           'days_since_last_corrective_on_asset', lw.days_since_last,
           'days_to_threshold', ne.days_to_threshold
         ) AS evidence
  FROM new_events ne
  JOIN OEE_DB.ERP.ASSET_MASTER am ON am.asset_id = ne.asset_id
  LEFT JOIN mode_history mh ON mh.event_id = ne.event_id
  LEFT JOIN last_wo lw ON lw.event_id = ne.event_id;

  -- Narrative backend: Cortex COMPLETE gated on trial accounts (platform-wide, June 2026);
  -- generated by external worker (src/llm_worker.py) pending access. Cortex version in git history.
  INSERT INTO OEE_DB.ANALYTICS.FINDINGS
        (event_id, asset_id, rca_summary, evidence_json, recommended_action)
  SELECT
    d.event_id, d.asset_id,
    '[PENDING_NARRATIVE]',
    d.evidence,
    CASE d.probable_mode
      WHEN 'BEARING_WEAR'        THEN 'Replace bearings; align and balance; investigate lubrication'
      WHEN 'COOLING_DEGRADATION' THEN 'Inspect and clean cooling path; verify airflow/filters'
      WHEN 'SENSOR_FAULT'        THEN 'Inspect sensor and cabling; route to data-quality queue'
      ELSE 'Investigate on site'
    END
  FROM _DOSSIER d;
  n_done := SQLROWCOUNT;

  -- 3) Advance the status machine.
  UPDATE OEE_DB.ANALYTICS.ANOMALY_EVENTS e
  SET status = 'INVESTIGATING'
  WHERE e.status = 'NEW'
    AND EXISTS (SELECT 1 FROM OEE_DB.ANALYTICS.FINDINGS f
                WHERE f.event_id = e.event_id);

  RETURN 'Diagnosed ' || n_done || ' event(s) of ' || n_new || ' new.';
END;
$$;

-- ── Chain into the task graph ───────────────────────────────────────────────
-- Child task: runs after DETECT_TASK in the same graph. Root must be
-- suspended when adding children (it currently is).

CREATE OR REPLACE TASK OEE_DB.ANALYTICS.DIAGNOSE_TASK
  USER_TASK_MANAGED_INITIAL_WAREHOUSE_SIZE = 'XSMALL'
  AFTER OEE_DB.ANALYTICS.DETECT_TASK
AS
  CALL OEE_DB.ANALYTICS.DIAGNOSE_FINDINGS();

-- Enable order: children first, then root.
-- ALTER TASK OEE_DB.ANALYTICS.DIAGNOSE_TASK RESUME;
-- ALTER TASK OEE_DB.ANALYTICS.DETECT_TASK RESUME;
